# Generated by Django 4.2.7 on 2023-11-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('timedate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('like', models.IntegerField(default=0)),
                ('kino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.kino')),
            ],
        ),
    ]
